runtime: python27
api_version: 1
threadsafe: true

skip_files:
- data/
- crawler/

handlers:
- url: /.*
  script: main.app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"